name: Build and Release AnimatedPokemon

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: python build.py dont_cache

      - name: Compress files for release
        run: |
          zip -r AnimatedPokemon.zip index.html
          zip -r AnimatedPokemon.zip main.css
          zip -r AnimatedPokemon.zip main.js
          zip -r AnimatedPokemon.zip pokemon.js
          zip -r AnimatedPokemon.zip Pokemon_Classic.ttf
          zip -r AnimatedPokemon.zip project.json
          zip -r AnimatedPokemon.zip preview.gif
          zip -r AnimatedPokemon.zip LICENSE.txt
          zip -r AnimatedPokemon.zip README.md
          zip -r AnimatedPokemon.zip sprites/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "AnimatedPokemon"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            AnimatedPokemon.zip
